author: Dan Salmon
baseURL: https://danthesalmon.com/
builddrafts: false
languageCode: en-us
publishdir: public
theme: clean
title: Dan [the] Salmon
disableHugoGeneratorInject: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: catppuccin-frappe
    noClasses: false
    guessSyntax: true

taxonomies:
  # site: sites
  format: formats
  tag: tags
  link_tag: 'link_tags'

permalinks:
  taxonomy:
    link_tags: /links/tags/
    formats: /links/formats/
  term:
    link_tags: /links/tags/:slug/
    formats: /links/formats/:slug/

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 50
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 52
    - identifier: links
      name: Links
      url: /links/
      weight: 55
    # - identifier: search
    #   name: Search
    #   url: /search/
    #   weight: 70
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 80