version: "3.3"

services:
  site:
    build: .
    container_name: personal-site
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - $PWD:/site
    entrypoint: /hugo serve --buildDrafts --port 8081 --bind 0.0.0.0
