name: Link
description: Post a new Link
title: "[link] "
labels: ["link"]
projects: []
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: Full URL (without tracking preferrably)
      placeholder: https://my.cool.other.blog/post/123
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: Title of thing
    validations:
      required: true
  - type: input
    id: pub_date
    attributes:
      label: Publish Date
      description: When was the content originally published? (ISO-8601)
      placeholder: "2024-06-19"
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Tags that describe the content, not format or venue (comma-separated)
      placeholder: xss,elevators,ios
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Text to add related to link
      placeholder: This is sweet
    validations:
      required: false
  - type: dropdown
    id: format
    attributes:
      label: Format
      description: What kind of thing is being linked to?
      multiple: false
      options:
        - article
        - document
        - paper
        - podcast
        - video
      default: 0
    validations:
      required: true
